input_key: "fusion"

# Optimizer
weight_decay: 1e-4

# Learning rate
lr_fusion: 1e-3
lr_encoder: 1e-4 # dovrei averne uno separato per ogni encoder?

# Freezing strategy
freeze_encoder_epochs: 5

# Scheduler
T_max: 30 
eta_min: 1e-6

# Early stopping
patience: 7

epochs: 30
batch_size: 16
num_workers: 0
val_split: 0.1
deterministic: false